Add m3u playlist download
n-thumann/IPTV-ReStream pull request #87
Opened 2020-12-15 14:40 UTC by Tereius

2020-12-15 17:50 UTC, n-thumann requested changes
Thank you very much for your contribution! That look´s like a useful feature! 👏 
I'd prefer removing the `simple` parameter, because it isn't accessible from the UI and I think it isn't much of a benefit to not include the channel number, title and image in the M3U. Of course it takes up three times more space, but that should be acceptable as we're talking kilobytes here 😊

2020-12-15 17:50 UTC, n-thumann commented on src/routes/station.ts
> +        "TRUE" === req.query.simple.toString().toUpperCase() ? true : false));
```suggestion
    res.write(m3uProvider.generateM3U(`${protocol}://${host}${pathPrefix}`));
```

2020-12-15 17:50 UTC, n-thumann commented on src/providers/m3u.ts
> +            }
```suggestion
            m3uString += ` tvg-chno="${chNum}" tvg-name="${station.title}" tvg-logo="${station.image}" group-title="IPTV"`;
```

2020-12-15 17:50 UTC, n-thumann commented on src/providers/m3u.ts
> +    public generateM3U(hostname: string, simple: boolean) {
```suggestion
    public generateM3U(hostname: string) {
```

2020-12-15 18:24 UTC, Tereius commented
I agree. Thank you for merging.

2020-12-17 16:50 UTC, merged

2020-12-17 17:14 UTC, n-thumann commented
Merged and pushed a new release ✌️